
public enum TokenType {
        WORD, NUMBER, SEPERATOR, PATTERN, WHILE, IF, DO, FOR, BREAK, CONTINUE,
        ELSE, RETURN, BEGIN, END, PRINT, PRINTF, NEXT, IN, DELETE, GETLINE, EXIT, NEXTFILE,
        FUNCTION, STRINGLITERAL, GREATEREQUAL, INCREMENT, DECREMENT, LESSEQUAL, EQUALEQUAL, NOTEQUAL,
        EXPONENTEQUAL, MODEQUAL, TIMESEQUAL, DIVIDEEQUAL, PLUSEQUAL, MINUSEQUAL, NOTMATCH, AND,
        APPEND, OROR, BRACESTART, BRACEEND, BRACKETSTART, BRACKETEND, PARENTHESISSTART, PARENTHESISEND,
        DOLLAR, MATCH, EQUAL, LESSTHAN, GREATERTHAN, NOT, PLUS, EXPONENT, MINUS, TERNARY, COLON,
        TIMES, DIVIDE, MODULO, OR, COMMA
}
